### ISSUE TITLE
SETTINGS_MODULE vs DJANGO_SETTINGS_MODULE

### ISSUE THREAD

**Issue by JonasGroeger** [DanielJDufour/djenv#1]
Hey!

In `    if k not in ['SETTINGS_MODULE']:`, shouldn't it be `DJANGO_SETTINGS_MODULE`?

**Comment by DanielJDufour** [comment]
Hey, you're right! @JonasGroeger , would you like to submit a Pull Request?  (If not, I can do it no problem).  Thank you for catching this!

**Comment by JonasGroeger** [comment]
Not really. I was just evaluating different tools, not using djenv unfortunately. I stuck with dynaconf

**Comment by DanielJDufour** [comment]
Just republished djenv with this fix.  Thank you again for catching this @JonasGroeger :-)
